# encoding: utf-8
# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

aguascalientes = Region.create(:name => 'Aguascalientes')
baja_california = Region.create(:name => 'Baja California')
baja_california_sur = Region.create(:name => 'Baja California Sur')
campeche = Region.create(:name => 'Campeche')
chiapas = Region.create(:name => 'Chiapas')
chihuahua = Region.create(:name => 'Chihuahua')
coahuila = Region.create(:name => 'Coahuila')
colima = Region.create(:name => 'Colima')
df = Region.create(:name => 'Distrito Federal')
durango = Region.create(:name => 'Durango')
guanajuato = Region.create(:name => 'Guanajuato')
guerrero = Region.create(:name => 'Guerrero')
hidalgo = Region.create(:name => 'Hidalgo')
jalisco = Region.create(:name => 'Jalisco')
edo_mex = Region.create(:name => 'Estado de México')
michoacan = Region.create(:name => 'Michoacán')
morelos = Region.create(:name => 'Morelos')
nayarit = Region.create(:name => 'Nayarit')
nuevo_leon = Region.create(:name => 'Nuevo León')
oaxaca = Region.create(:name => 'Oaxaca')
puebla = Region.create(:name => 'Puebla')
queretaro = Region.create(:name => 'Querétaro')
qintana_roo = Region.create(:name => 'Quintana Roo')
san_luis_potosi = Region.create(:name => 'San Luis Potosí')
sinaloa = Region.create(:name => 'Sinaloa')
sonora = Region.create(:name => 'Sonora')
tabasco = Region.create(:name => 'Tabasco')
tamaulipas = Region.create(:name => 'Tamaulipas')
tlaxcala = Region.create(:name => 'Tlaxcala')
veracruz = Region.create(:name => 'Veracruz')
yucatan = Region.create(:name => 'Yucatán')
zacatecas = Region.create(:name => 'Zacatecas')
